### ISSUE TITLE
Prerig | bespoke joint handle and better tracking

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#136]
- [x] with the lots of form handle setup, the pre handle tracking is way off
- [x] joint specific handle placement

**Comment by jjburton** [comment]
### Better tracking

- [ ] Limb

**Comment by jjburton** [comment]
### Bespoke joint handle setup

- [ ] Segment
- [ ] LIMB
- [ ] Head (neck)
- [ ] Handle

**Comment by jjburton** [comment]
### Segment

**Comment by jjburton** [comment]
### Selection Issues
Generally it's difficult to select all of a given type of handle types

**Comment by jjburton** [comment]
### Head

reload(mBlock.p_blockModule)
mBlock.atBlockModule('create_jointHelpers',8)
mBlock.atBlockModule('create_jointHelpers',5)

- pulled joint handle making out of prerig

- [ ] prerig | need to generate a new track curve
- [ ] get positions
- [ ] create joint handles
- [ ] name from skeleton setup
- [ ] wire
- [ ] rebuildable with change in pos

- [ ] skeletonize

- [ ] added to ui in block editor

**Comment by jjburton** [comment]
### LIMB

reload(mBlock.p_blockModule)
mBlock.atBlockModule('create_jointHelpers',8)
mBlock.atBlockModule('create_jointHelpers',5)

- pulled joint handle making out of prerig

- [ ] prerig | need to generate a new track curve
- [ ] get positions
- [ ] create joint handles
- [ ] name from skeleton setup
- [ ] wire
- [ ] rebuildable with change in pos

- [ ] skeletonize

- [ ]] added to ui in block editor
