### ISSUE TITLE
Weekend of 1.22.22

### ISSUE THREAD

**Issue by jjburton** [jjburton/cgmTools#314]
- [ ] #309 | might need multiple asset check at export to avoid a fail
- [ ] #312 / #310  / #304 | head skin cluster on unified proxy build
- [ ] #308 | Need to hook up with Bren to see when exactly this is hitting
- [ ] #311 
- [ ] #313
